# Generated by Django 6.0.6 on 2026-06-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('dhtm', 'Diploma in Hospitality and Tourism Management'), ('dbm', 'Diploma in Business Management'), ('dcsm', 'Diploma in Chain and Supply Management'), ('adhtm', 'Advanced Diploma in Hospitality and Tourism Management'), ('adbm', 'Advanced Diploma in Business Management'), ('adcsm', 'Advanced Diploma in Chain and Supply Management')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
